version: '3'

services:
  go:
    image: golang:1.17.6
    volumes:
      - .:/go/src
    ports:
      - 1234:1234
    tty: true

  rabbitmq:
    image: rabbitmq:3.9.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
